image: node:15.4

stages:
  - deploy

publish-npm:
  stage: deploy
  script:
    - npm config set -- '//gitlab.nekosyndicate.com/api/v4/projects/35/packages/npm/:_authToken' ${CI_JOB_TOKEN}
    - npm publish --verbose


