image: node:latest

stages:
  - deploy

publish-npm:
  stage: deploy
  script:
    - npm config set //gitlab.nekosyndicate.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}
    - npm config set @scope:registry https://gitlab.nekosyndicate.com/api/v4/packages/npm/
    - npm publish
