image: node:latest

stages:
  - deploy

publish-npm:
  stage: deploy
  script:
    - npm config set //${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}
    - npm config set _authToken=${CI_JOB_TOKEN}
    - npm publish

