image: node:20.14.0

stages:
  - deploy

publish-npm:
  stage: deploy
  script:
    - npm install
    - npm run build
    - echo "@danielb:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm publish


