image: node:latest

stages:
  - deploy

publish-npm:
  stage: deploy
  script:
    - npm config set @danielb:registry https://gitlab.nekosyndicate.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm
    - npm config set //gitlab.nekosyndicate.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm:_authToken ${CI_JOB_TOKEN}
    - npm publish